#global
EPOCHS = 1024
GEN_LEARNING_RATE = 1e-3
DISC_LEARNING_RATE = 1e-3
DATA_ELEMENTS = 2 ** 16

DROPOUT = 0.0
#generator
GEN_SEED_SIZE = 16

GEN_L0_SIZE = 16
GEN_L1_SIZE = 16

GEN_OUTPUT_SIZE = 2;

#gan discriminator
DISC_L0_SIZE = 8
DISC_L1_SIZE = 8

GAN_BATCH_SIZE = 256

#dgan discriminator
DGAN_COMPARE_ENTRIES = 4

DGAN_L0_SIZE = DISC_L0_SIZE * DGAN_COMPARE_ENTRIES;
DGAN_L1_SIZE = DISC_L1_SIZE * DGAN_COMPARE_ENTRIES;

DGAN_BATCH_SIZE = 256 * DGAN_COMPARE_ENTRIES
